# -*- coding: utf-8 -*-
"""DireccionesUbicacion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tt1NCZZl39Xd0E2jIr46mAJKOuVs6rW0
"""

import pandas as pd
import numpy as np
from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="PersonaEvoqTest")















import pandas as pd
import numpy as np
from geopy.geocoders import Nominatim

df1 = pd.read_excel('01_DatosEntrada/202001_users_.xlsx')
df2 = pd.read_excel('01_DatosEntrada/202002_users_.xlsx')
df3 = pd.read_excel('01_DatosEntrada/202003_users_.xlsx')
df4 = pd.read_excel('01_DatosEntrada/202004_users_.xlsx')
df5 = pd.read_excel('01_DatosEntrada/202005_users_.xlsx')

df2.head()

df = pd.concat([df1, df2, df3, df4, df5])

df.head(2)



dfb = df[0:30]
new_cols = ['Loc_direccionCompleta', 'Loc_latitude', 'Loc_longitude', 'Loc_address', 'Loc_barrio', 'Loc_Zona', 'Loc_Ciudad', 'Loc_estado', 'Loc_pais']
new_vals = [None, None, None, None, None, None, None, None, None]
dfb = dfb.reindex(columns=dfb.columns.tolist() + new_cols)   # add empty cols
dfb[new_cols] = new_vals  # multi-column assignment works for existing cols
dfb.info()

geolocator = Nominatim(user_agent="Prueba")

for index, row in dfb.iterrows():
    direccionCompleta = (str(row["Direccion "]) + ", " + str(row["Barrio "])+ ", " + str( row["Ciudad "]))
    direccion = (str(row["Barrio "])+ ", " + str( row["Ciudad "]))
    
    dfb['Loc_direccionCompleta'][index] = str(direccionCompleta)
    
    try:
        location = geolocator.geocode(direccion, addressdetails=True)  
        if location:
            
            coordinates = str(location.latitude) + ", " + str(location.longitude)
            dfb['Loc_latitude'][index] =location.latitude
            dfb['Loc_longitude'][index] =location.longitude
            
            #location = geolocator.reverse(coordinates)
            address = location.raw['address'] 
            
            dfb['Loc_address'][index] = str(address)
            dfb['Loc_barrio'][index]  = address.get('neighbourhood', '')
            dfb['Loc_Zona'][index]    = address.get('suburb', '')
            dfb['Loc_Ciudad'][index]  = address.get('city', '')
            dfb['Loc_estado'][index]  = address.get('state', '')
            
            #if (index%100 == 0):
            print(index)

    
    except Exception:
        raise Exception("Location error")

dfb.head()

dfb.to_excel (r'02_datosSalida/personasClasificadas.xlsx', index = None, header=True)

!pip install -U googlemaps

import googlemaps
from datetime import datetime

gmaps = googlemaps.Client(key='AIzaSyCQYVgh12Mdi0H6CYDln0rW2rdAgWr0y38')

# Geocoding an address
geocode_result = gmaps.geocode('Calle 38 #64A-26, Medellin')

# Look up an address with reverse geocoding
reverse_geocode_result = gmaps.reverse_geocode((6.240983519708498, -75.58329768029151))

# Request directions via public transit
now = datetime.now()
directions_result = gmaps.directions('Calle 38 #64A-26, Medellin',
                                     "Arkix, medellin",
                                     mode="transit",
                                     departure_time=now)

geocode_result

reverse_geocode_result









